### ISSUE TITLE
File watching of default.txt on MacOS doesn't use native file systems handling, takes up to 2 seconds per poll

### ISSUE THREAD

**Issue by twadzins** [csabagabor/Keep-Unit-Test-Running-IntelliJ-Plugin#1]
Currently, the plugin uses the Java WatchService, which doesn't use fast native file system hooks for MacOS.

I'll submit a PR for fixing this.

**Comment by twadzins** [comment]
Here's a PR for this:
https://github.com/csabagabor/Keep-Unit-Test-Running-IntelliJ-Plugin/pull/2

**Comment by twadzins** [comment]
Here's a screencast showing the fix running on MacOS
https://github.com/csabagabor/Keep-Unit-Test-Running-IntelliJ-Plugin/assets/1863335/a5d2e4f8-84fc-495e-9ec3-ebbe4f339b40

**Comment by csabagabor** [comment]
Thank you for the pull request.

Closing as fixed.
