### ISSUE TITLE
Each run of "Keep-Unit-Test-Running" after the first starts up a new java process

### ISSUE THREAD

**Issue by twadzins** [csabagabor/Keep-Unit-Test-Running-IntelliJ-Plugin#3]
Each run of "Keep-Unit-Test-Running" after the first starts up a new java process. These extra processes build up and use up system memory until the overall test run is complete.

I'll submit a PR for this issue.

**Comment by csabagabor** [comment]
Thank you for the [Pull request](https://github.com/csabagabor/Keep-Unit-Test-Running-IntelliJ-Plugin/pull/4 ): 

Closing as fixed.
